-- TABLA: EMPLEADOS
-- DESCRIPCIÓN:
-- Almacena la información básica de los empleados
-- del sistema.

-- IDENTIFICADOR ÚNICO DEL EMPLEADO
    -- NUMBER:
    -- Tipo numérico en Oracle.
    --
    -- GENERATED BY DEFAULT AS IDENTITY:
    -- Genera automáticamente valores incrementales.
    --
    -- PRIMARY KEY:
    -- Define la llave primaria de la tabla.
CREATE TABLE EMPLEADOS (
    ID_EMPLEADOS NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

      -- NOMBRE DEL EMPLEADO
    --
    -- VARCHAR2(100 CHAR):
    -- Cadena de texto con máximo 100 caracteres.
    --
    -- NOT NULL:
    -- Campo obligatorio.
    
    NOMBRE VARCHAR2(100 CHAR) NOT NULL,

    -- PUESTO O CARGO DEL EMPLEADO
    --
    -- Ejemplos:
    -- - Desarrollador
    -- - QA
    -- - DevOps
    
    PUESTO VARCHAR2(100 CHAR) NOT NULL,

     -- SALARIO DEL EMPLEADO
    --
    -- NUMBER(10,2):
    -- Hasta 10 dígitos y 2 decimales.
    --
    -- Ejemplos válidos:
    -- 15000.00
    -- 2500.50
    
    SALARIO NUMBER(10,2) NOT NULL
);

-- ÍNDICE:
-- Mejora el rendimiento de búsquedas por nombre.

ALTER TABLE EMPLEADOS
ADD CONSTRAINT CHK_SALARIO_POSITIVO
CHECK (SALARIO > 0);

-- ÍNDICE:
-- Mejora el rendimiento de búsquedas por nombre.

CREATE INDEX IDX_EMPLEADOS_NOMBRE
ON EMPLEADOS(NOMBRE);

-- ÍNDICE:
-- Mejora el rendimiento de búsquedas por puesto.

CREATE INDEX IDX_EMPLEADOS_PUESTO
ON EMPLEADOS(PUESTO);

-- DATOS DE PRUEBA

INSERT INTO EMPLEADOS (NOMBRE, PUESTO, SALARIO)
VALUES ('Juan Perez', 'Desarrollador Java', 25000);

INSERT INTO EMPLEADOS (NOMBRE, PUESTO, SALARIO)
VALUES ('Maria Lopez', 'QA Analyst', 22000);

INSERT INTO EMPLEADOS (NOMBRE, PUESTO, SALARIO)
VALUES ('Carlos Hernandez', 'DevOps Engineer', 30000);

-- GUARDA LOS CAMBIOS EN LA BASE DE DATOS

COMMIT;

-- CONSULTA PARA VALIDAR LOS DATOS INSERTADOS

SELECT * FROM EMPLEADOS;